export const COUNTRY_CODES = [
  { code: "+1", country: "US/CA", flag: "🇺🇸" },
  { code: "+44", country: "UK", flag: "🇬🇧" },
  { code: "+91", country: "IN", flag: "🇮🇳" },
  { code: "+86", country: "CN", flag: "🇨🇳" },
  { code: "+81", country: "JP", flag: "🇯🇵" },
  { code: "+82", country: "KR", flag: "🇰🇷" },
  { code: "+63", country: "PH", flag: "🇵🇭" },
  { code: "+84", country: "VN", flag: "🇻🇳" },
  { code: "+66", country: "TH", flag: "🇹🇭" },
  { code: "+62", country: "ID", flag: "🇮🇩" },
  { code: "+60", country: "MY", flag: "🇲🇾" },
  { code: "+65", country: "SG", flag: "🇸🇬" },
  { code: "+880", country: "BD", flag: "🇧🇩" },
  { code: "+92", country: "PK", flag: "🇵🇰" },
  { code: "+94", country: "LK", flag: "🇱🇰" },
  { code: "+977", country: "NP", flag: "🇳🇵" },
  { code: "+971", country: "AE", flag: "🇦🇪" },
  { code: "+966", country: "SA", flag: "🇸🇦" },
  { code: "+972", country: "IL", flag: "🇮🇱" },
  { code: "+90", country: "TR", flag: "🇹🇷" },
  { code: "+20", country: "EG", flag: "🇪🇬" },
  { code: "+234", country: "NG", flag: "🇳🇬" },
  { code: "+254", country: "KE", flag: "🇰🇪" },
  { code: "+27", country: "ZA", flag: "🇿🇦" },
  { code: "+251", country: "ET", flag: "🇪🇹" },
  { code: "+255", country: "TZ", flag: "🇹🇿" },
  { code: "+233", country: "GH", flag: "🇬🇭" },
  { code: "+52", country: "MX", flag: "🇲🇽" },
  { code: "+55", country: "BR", flag: "🇧🇷" },
  { code: "+57", country: "CO", flag: "🇨🇴" },
  { code: "+51", country: "PE", flag: "🇵🇪" },
  { code: "+54", country: "AR", flag: "🇦🇷" },
  { code: "+56", country: "CL", flag: "🇨🇱" },
  { code: "+58", country: "VE", flag: "🇻🇪" },
  { code: "+53", country: "CU", flag: "🇨🇺" },
  { code: "+33", country: "FR", flag: "🇫🇷" },
  { code: "+49", country: "DE", flag: "🇩🇪" },
  { code: "+39", country: "IT", flag: "🇮🇹" },
  { code: "+34", country: "ES", flag: "🇪🇸" },
  { code: "+351", country: "PT", flag: "🇵🇹" },
  { code: "+31", country: "NL", flag: "🇳🇱" },
  { code: "+46", country: "SE", flag: "🇸🇪" },
  { code: "+47", country: "NO", flag: "🇳🇴" },
  { code: "+48", country: "PL", flag: "🇵🇱" },
  { code: "+380", country: "UA", flag: "🇺🇦" },
  { code: "+7", country: "RU", flag: "🇷🇺" },
  { code: "+61", country: "AU", flag: "🇦🇺" },
  { code: "+64", country: "NZ", flag: "🇳🇿" },
  { code: "+509", country: "HT", flag: "🇭🇹" },
  { code: "+1-787", country: "PR", flag: "🇵🇷" },
];

export interface ConditionWithICD {
  key: string;
  icd10: string;
}

export const CONDITIONS_ICD10: ConditionWithICD[] = [
  { key: "hypertension", icd10: "I10" },
  { key: "type2Diabetes", icd10: "E11.9" },
  { key: "asthma", icd10: "J45.909" },
  { key: "depression", icd10: "F32.9" },
  { key: "anxiety", icd10: "F41.9" },
  { key: "hyperlipidemia", icd10: "E78.5" },
  { key: "gerd", icd10: "K21.0" },
  { key: "osteoarthritis", icd10: "M19.90" },
  { key: "hypothyroidism", icd10: "E03.9" },
  { key: "hyperthyroidism", icd10: "E05.90" },
  { key: "migraine", icd10: "G43.909" },
  { key: "obesity", icd10: "E66.9" },
  { key: "copd", icd10: "J44.1" },
  { key: "heartDisease", icd10: "I25.10" },
  { key: "kidneyDisease", icd10: "N18.9" },
  { key: "osteoporosis", icd10: "M81.0" },
  { key: "sleepApnea", icd10: "G47.33" },
  { key: "afib", icd10: "I48.91" },
  { key: "stroke", icd10: "I63.9" },
  { key: "ironDeficiency", icd10: "D50.9" },
  { key: "vitaminD", icd10: "E55.9" },
  { key: "allergicRhinitis", icd10: "J30.9" },
  { key: "backNeckPain", icd10: "M54.5" },
  { key: "coronaryArteryDisease", icd10: "I25.10" },
  { key: "recentPneumonia", icd10: "J18.9" },
  { key: "dementia", icd10: "F03.90" },
  { key: "lungCancer", icd10: "C34.90" },
  { key: "colorectalCancer", icd10: "C18.9" },
  { key: "tuberculosis", icd10: "A15.9" },
  { key: "cirrhosis", icd10: "K74.60" },
  { key: "fattyLiver", icd10: "K76.0" },
  { key: "hiv", icd10: "B20" },
  { key: "hepatitisC", icd10: "B18.2" },
  { key: "hepatitisB", icd10: "B18.1" },
];

export interface SurgeryWithCPT {
  key: string;
  cpt: string;
}

export const SURGERIES_CPT: SurgeryWithCPT[] = [
  { key: "surgCataract", cpt: "66984" },
  { key: "surgCSection", cpt: "59510" },
  { key: "surgColonoscopy", cpt: "45378" },
  { key: "surgKneeReplacement", cpt: "27447" },
  { key: "surgHipReplacement", cpt: "27130" },
  { key: "surgShoulderReplacement", cpt: "23472" },
  { key: "surgCholecystectomy", cpt: "47562" },
  { key: "surgHerniaRepair", cpt: "49505" },
  { key: "surgAppendectomy", cpt: "44970" },
  { key: "surgCoronaryBypass", cpt: "33533" },
  { key: "surgHysterectomy", cpt: "58571" },
  { key: "surgHeartStent", cpt: "92928" },
  { key: "surgTonsillectomy", cpt: "42826" },
  { key: "surgSpinalFusion", cpt: "22612" },
  { key: "surgRotatorCuff", cpt: "29827" },
  { key: "surgCarpalTunnel", cpt: "64721" },
  { key: "surgACLRepair", cpt: "29888" },
  { key: "surgLumpectomy", cpt: "19301" },
  { key: "surgMastectomy", cpt: "19303" },
  { key: "surgEndoscopy", cpt: "43239" },
  { key: "surgWisdomTooth", cpt: "D7240" },
  { key: "surgHemorrhoid", cpt: "46255" },
  { key: "surgArthroscopy", cpt: "29881" },
];

export const COMMON_ALLERGENS = [
  { name: "Penicillin", category: "Drug" },
  { name: "Amoxicillin", category: "Drug" },
  { name: "Sulfa Drugs (Sulfonamides)", category: "Drug" },
  { name: "Aspirin", category: "Drug" },
  { name: "Ibuprofen / NSAIDs", category: "Drug" },
  { name: "Codeine", category: "Drug" },
  { name: "Cephalosporins", category: "Drug" },
  { name: "Latex", category: "Environmental" },
  { name: "Peanuts", category: "Food" },
  { name: "Tree Nuts (Almonds, Walnuts, Cashews)", category: "Food" },
  { name: "Shellfish (Shrimp, Crab, Lobster)", category: "Food" },
  { name: "Fish", category: "Food" },
  { name: "Eggs", category: "Food" },
  { name: "Milk / Dairy", category: "Food" },
  { name: "Wheat / Gluten", category: "Food" },
  { name: "Soy", category: "Food" },
  { name: "Sesame", category: "Food" },
  { name: "Bee Stings / Insect Venom", category: "Environmental" },
  { name: "Dust Mites", category: "Environmental" },
  { name: "Pollen (Grass, Tree, Ragweed)", category: "Environmental" },
  { name: "Mold / Mildew", category: "Environmental" },
  { name: "Pet Dander (Cat, Dog)", category: "Environmental" },
  { name: "Contrast Dye (Iodine-based)", category: "Drug" },
  { name: "Morphine / Opioids", category: "Drug" },
  { name: "Other", category: "Other" },
];

export interface CommonMedication {
  name: string;
  genericName: string;
  forCondition: string;
  icd10: string;
  strengths: string[];
  dosing: string[];
}

export const COMMON_MEDICATIONS: CommonMedication[] = [
  { name: "Lisinopril", genericName: "Lisinopril", forCondition: "Hypertension", icd10: "I10", strengths: ["2.5mg", "5mg", "10mg", "20mg", "40mg"], dosing: ["Once Daily"] },
  { name: "Amlodipine (Norvasc)", genericName: "Amlodipine", forCondition: "Hypertension", icd10: "I10", strengths: ["2.5mg", "5mg", "10mg"], dosing: ["Once Daily"] },
  { name: "Losartan (Cozaar)", genericName: "Losartan", forCondition: "Hypertension", icd10: "I10", strengths: ["25mg", "50mg", "100mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Metoprolol (Lopressor)", genericName: "Metoprolol", forCondition: "Hypertension / Heart Rate", icd10: "I10", strengths: ["25mg", "50mg", "100mg", "200mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Hydrochlorothiazide (HCTZ)", genericName: "Hydrochlorothiazide", forCondition: "Hypertension", icd10: "I10", strengths: ["12.5mg", "25mg", "50mg"], dosing: ["Once Daily"] },
  { name: "Valsartan (Diovan)", genericName: "Valsartan", forCondition: "Hypertension", icd10: "I10", strengths: ["40mg", "80mg", "160mg", "320mg"], dosing: ["Once Daily"] },
  { name: "Carvedilol (Coreg)", genericName: "Carvedilol", forCondition: "Heart Failure / HTN", icd10: "I50.9", strengths: ["3.125mg", "6.25mg", "12.5mg", "25mg"], dosing: ["Twice Daily"] },
  { name: "Metformin (Glucophage)", genericName: "Metformin", forCondition: "Type 2 Diabetes", icd10: "E11.9", strengths: ["500mg", "850mg", "1000mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Glipizide (Glucotrol)", genericName: "Glipizide", forCondition: "Type 2 Diabetes", icd10: "E11.9", strengths: ["2.5mg", "5mg", "10mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Insulin Glargine (Lantus)", genericName: "Insulin Glargine", forCondition: "Diabetes", icd10: "E11.9", strengths: ["100 units/mL"], dosing: ["Once Daily (bedtime)"] },
  { name: "Empagliflozin (Jardiance)", genericName: "Empagliflozin", forCondition: "Type 2 Diabetes", icd10: "E11.9", strengths: ["10mg", "25mg"], dosing: ["Once Daily"] },
  { name: "Semaglutide (Ozempic)", genericName: "Semaglutide", forCondition: "Type 2 Diabetes / Obesity", icd10: "E11.9", strengths: ["0.25mg", "0.5mg", "1mg", "2mg"], dosing: ["Once Weekly"] },
  { name: "Sitagliptin (Januvia)", genericName: "Sitagliptin", forCondition: "Type 2 Diabetes", icd10: "E11.9", strengths: ["25mg", "50mg", "100mg"], dosing: ["Once Daily"] },
  { name: "Atorvastatin (Lipitor)", genericName: "Atorvastatin", forCondition: "Hyperlipidemia", icd10: "E78.5", strengths: ["10mg", "20mg", "40mg", "80mg"], dosing: ["Once Daily"] },
  { name: "Rosuvastatin (Crestor)", genericName: "Rosuvastatin", forCondition: "Hyperlipidemia", icd10: "E78.5", strengths: ["5mg", "10mg", "20mg", "40mg"], dosing: ["Once Daily"] },
  { name: "Simvastatin (Zocor)", genericName: "Simvastatin", forCondition: "Hyperlipidemia", icd10: "E78.5", strengths: ["5mg", "10mg", "20mg", "40mg"], dosing: ["Once Daily (evening)"] },
  { name: "Ezetimibe (Zetia)", genericName: "Ezetimibe", forCondition: "Hyperlipidemia", icd10: "E78.5", strengths: ["10mg"], dosing: ["Once Daily"] },
  { name: "Levothyroxine (Synthroid)", genericName: "Levothyroxine", forCondition: "Hypothyroidism", icd10: "E03.9", strengths: ["25mcg", "50mcg", "75mcg", "88mcg", "100mcg", "112mcg", "125mcg", "137mcg", "150mcg", "175mcg", "200mcg"], dosing: ["Once Daily (morning, empty stomach)"] },
  { name: "Methimazole (Tapazole)", genericName: "Methimazole", forCondition: "Hyperthyroidism", icd10: "E05.90", strengths: ["5mg", "10mg", "20mg"], dosing: ["Once Daily", "Twice Daily", "Three Times Daily"] },
  { name: "Omeprazole (Prilosec)", genericName: "Omeprazole", forCondition: "GERD", icd10: "K21.0", strengths: ["10mg", "20mg", "40mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Pantoprazole (Protonix)", genericName: "Pantoprazole", forCondition: "GERD", icd10: "K21.0", strengths: ["20mg", "40mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Famotidine (Pepcid)", genericName: "Famotidine", forCondition: "GERD", icd10: "K21.0", strengths: ["10mg", "20mg", "40mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Albuterol Inhaler (ProAir)", genericName: "Albuterol", forCondition: "Asthma / COPD", icd10: "J45.909", strengths: ["90mcg/actuation"], dosing: ["Every 4-6 hours as needed"] },
  { name: "Fluticasone Inhaler (Flovent)", genericName: "Fluticasone", forCondition: "Asthma", icd10: "J45.909", strengths: ["44mcg", "110mcg", "220mcg"], dosing: ["Twice Daily"] },
  { name: "Montelukast (Singulair)", genericName: "Montelukast", forCondition: "Asthma / Allergies", icd10: "J45.909", strengths: ["4mg", "5mg", "10mg"], dosing: ["Once Daily (evening)"] },
  { name: "Tiotropium (Spiriva)", genericName: "Tiotropium", forCondition: "COPD", icd10: "J44.1", strengths: ["1.25mcg", "2.5mcg"], dosing: ["Once Daily"] },
  { name: "Sertraline (Zoloft)", genericName: "Sertraline", forCondition: "Depression / Anxiety", icd10: "F32.9", strengths: ["25mg", "50mg", "100mg", "150mg", "200mg"], dosing: ["Once Daily"] },
  { name: "Escitalopram (Lexapro)", genericName: "Escitalopram", forCondition: "Depression / Anxiety", icd10: "F32.9", strengths: ["5mg", "10mg", "20mg"], dosing: ["Once Daily"] },
  { name: "Fluoxetine (Prozac)", genericName: "Fluoxetine", forCondition: "Depression", icd10: "F32.9", strengths: ["10mg", "20mg", "40mg", "60mg"], dosing: ["Once Daily"] },
  { name: "Bupropion (Wellbutrin)", genericName: "Bupropion", forCondition: "Depression", icd10: "F32.9", strengths: ["75mg", "100mg", "150mg", "300mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Duloxetine (Cymbalta)", genericName: "Duloxetine", forCondition: "Depression / Neuropathy", icd10: "F32.9", strengths: ["20mg", "30mg", "60mg"], dosing: ["Once Daily"] },
  { name: "Venlafaxine (Effexor)", genericName: "Venlafaxine", forCondition: "Depression / Anxiety", icd10: "F41.9", strengths: ["37.5mg", "75mg", "150mg", "225mg"], dosing: ["Once Daily"] },
  { name: "Buspirone (Buspar)", genericName: "Buspirone", forCondition: "Anxiety", icd10: "F41.9", strengths: ["5mg", "10mg", "15mg", "30mg"], dosing: ["Twice Daily", "Three Times Daily"] },
  { name: "Alprazolam (Xanax)", genericName: "Alprazolam", forCondition: "Anxiety", icd10: "F41.9", strengths: ["0.25mg", "0.5mg", "1mg", "2mg"], dosing: ["As Needed", "Twice Daily", "Three Times Daily"] },
  { name: "Gabapentin (Neurontin)", genericName: "Gabapentin", forCondition: "Neuropathy / Seizures", icd10: "G62.9", strengths: ["100mg", "300mg", "400mg", "600mg", "800mg"], dosing: ["Three Times Daily"] },
  { name: "Pregabalin (Lyrica)", genericName: "Pregabalin", forCondition: "Neuropathy / Fibromyalgia", icd10: "G62.9", strengths: ["25mg", "50mg", "75mg", "100mg", "150mg", "200mg", "300mg"], dosing: ["Twice Daily", "Three Times Daily"] },
  { name: "Warfarin (Coumadin)", genericName: "Warfarin", forCondition: "Blood Clot Prevention", icd10: "Z79.01", strengths: ["1mg", "2mg", "2.5mg", "3mg", "4mg", "5mg", "6mg", "7.5mg", "10mg"], dosing: ["Once Daily"] },
  { name: "Apixaban (Eliquis)", genericName: "Apixaban", forCondition: "AFib / DVT Prevention", icd10: "I48.91", strengths: ["2.5mg", "5mg"], dosing: ["Twice Daily"] },
  { name: "Rivaroxaban (Xarelto)", genericName: "Rivaroxaban", forCondition: "AFib / DVT Prevention", icd10: "I48.91", strengths: ["10mg", "15mg", "20mg"], dosing: ["Once Daily"] },
  { name: "Clopidogrel (Plavix)", genericName: "Clopidogrel", forCondition: "Heart Attack / Stroke Prevention", icd10: "Z79.02", strengths: ["75mg"], dosing: ["Once Daily"] },
  { name: "Aspirin (Low-dose)", genericName: "Aspirin", forCondition: "Heart Disease Prevention", icd10: "Z79.82", strengths: ["81mg", "325mg"], dosing: ["Once Daily"] },
  { name: "Acetaminophen (Tylenol)", genericName: "Acetaminophen", forCondition: "Pain / Fever", icd10: "R52", strengths: ["325mg", "500mg", "650mg ER"], dosing: ["Every 4-6 hours as needed", "Every 8 hours (ER)"] },
  { name: "Ibuprofen (Advil/Motrin)", genericName: "Ibuprofen", forCondition: "Pain / Inflammation", icd10: "R52", strengths: ["200mg", "400mg", "600mg", "800mg"], dosing: ["Every 6-8 hours as needed"] },
  { name: "Naproxen (Aleve)", genericName: "Naproxen", forCondition: "Pain / Inflammation", icd10: "M19.90", strengths: ["220mg", "250mg", "375mg", "500mg"], dosing: ["Twice Daily"] },
  { name: "Meloxicam (Mobic)", genericName: "Meloxicam", forCondition: "Osteoarthritis", icd10: "M19.90", strengths: ["7.5mg", "15mg"], dosing: ["Once Daily"] },
  { name: "Prednisone", genericName: "Prednisone", forCondition: "Inflammation / Autoimmune", icd10: "M79.3", strengths: ["1mg", "2.5mg", "5mg", "10mg", "20mg", "50mg"], dosing: ["Once Daily", "As directed (taper)"] },
  { name: "Cetirizine (Zyrtec)", genericName: "Cetirizine", forCondition: "Allergies", icd10: "J30.9", strengths: ["5mg", "10mg"], dosing: ["Once Daily"] },
  { name: "Loratadine (Claritin)", genericName: "Loratadine", forCondition: "Allergies", icd10: "J30.9", strengths: ["10mg"], dosing: ["Once Daily"] },
  { name: "Fexofenadine (Allegra)", genericName: "Fexofenadine", forCondition: "Allergies", icd10: "J30.9", strengths: ["60mg", "180mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Fluticasone Nasal (Flonase)", genericName: "Fluticasone Nasal", forCondition: "Allergic Rhinitis", icd10: "J30.9", strengths: ["50mcg/spray"], dosing: ["1-2 sprays each nostril daily"] },
  { name: "Tamsulosin (Flomax)", genericName: "Tamsulosin", forCondition: "BPH (Enlarged Prostate)", icd10: "N40.1", strengths: ["0.4mg"], dosing: ["Once Daily"] },
  { name: "Finasteride (Proscar)", genericName: "Finasteride", forCondition: "BPH / Hair Loss", icd10: "N40.1", strengths: ["1mg", "5mg"], dosing: ["Once Daily"] },
  { name: "Sumatriptan (Imitrex)", genericName: "Sumatriptan", forCondition: "Migraine", icd10: "G43.909", strengths: ["25mg", "50mg", "100mg"], dosing: ["As Needed (max 200mg/day)"] },
  { name: "Topiramate (Topamax)", genericName: "Topiramate", forCondition: "Migraine Prevention / Seizures", icd10: "G43.909", strengths: ["25mg", "50mg", "100mg", "200mg"], dosing: ["Twice Daily"] },
  { name: "Alendronate (Fosamax)", genericName: "Alendronate", forCondition: "Osteoporosis", icd10: "M81.0", strengths: ["35mg", "70mg"], dosing: ["Once Weekly"] },
  { name: "Cyclobenzaprine (Flexeril)", genericName: "Cyclobenzaprine", forCondition: "Muscle Spasm", icd10: "M62.838", strengths: ["5mg", "10mg"], dosing: ["Three Times Daily"] },
  { name: "Trazodone (Desyrel)", genericName: "Trazodone", forCondition: "Insomnia / Depression", icd10: "G47.00", strengths: ["50mg", "100mg", "150mg"], dosing: ["Once Daily (bedtime)"] },
  { name: "Zolpidem (Ambien)", genericName: "Zolpidem", forCondition: "Insomnia", icd10: "G47.00", strengths: ["5mg", "10mg"], dosing: ["Once Daily (bedtime)"] },
  { name: "Furosemide (Lasix)", genericName: "Furosemide", forCondition: "Edema / Heart Failure", icd10: "I50.9", strengths: ["20mg", "40mg", "80mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Spironolactone (Aldactone)", genericName: "Spironolactone", forCondition: "Heart Failure / Edema", icd10: "I50.9", strengths: ["25mg", "50mg", "100mg"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Potassium Chloride (K-Dur)", genericName: "Potassium Chloride", forCondition: "Low Potassium", icd10: "E87.6", strengths: ["10mEq", "20mEq"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Ferrous Sulfate (Iron)", genericName: "Ferrous Sulfate", forCondition: "Iron Deficiency Anemia", icd10: "D50.9", strengths: ["325mg (65mg elemental)"], dosing: ["Once Daily", "Twice Daily"] },
  { name: "Vitamin D3 (Cholecalciferol)", genericName: "Cholecalciferol", forCondition: "Vitamin D Deficiency", icd10: "E55.9", strengths: ["1000 IU", "2000 IU", "5000 IU", "50000 IU"], dosing: ["Once Daily", "Once Weekly (50000 IU)"] },
  { name: "Methotrexate", genericName: "Methotrexate", forCondition: "Rheumatoid Arthritis", icd10: "M06.9", strengths: ["2.5mg", "7.5mg", "10mg", "15mg", "20mg", "25mg"], dosing: ["Once Weekly"] },
  { name: "Donepezil (Aricept)", genericName: "Donepezil", forCondition: "Dementia / Alzheimer's", icd10: "F03.90", strengths: ["5mg", "10mg", "23mg"], dosing: ["Once Daily (bedtime)"] },
  { name: "Amoxicillin", genericName: "Amoxicillin", forCondition: "Bacterial Infection", icd10: "J06.9", strengths: ["250mg", "500mg", "875mg"], dosing: ["Twice Daily", "Three Times Daily"] },
];

export const SOCIAL_HISTORY_ICD: Record<string, { label: string; icd10: string }> = {
  "current-daily": { label: "Current daily smoker", icd10: "F17.210" },
  "current-occasional": { label: "Current occasional smoker", icd10: "F17.210" },
  "former": { label: "Former smoker", icd10: "Z87.891" },
  "never": { label: "Never smoker", icd10: "Z72.0" },
  "none-alcohol": { label: "No alcohol use", icd10: "Z72.89" },
  "occasional": { label: "Occasional alcohol use", icd10: "Z72.89" },
  "moderate": { label: "Moderate alcohol use", icd10: "Z72.89" },
  "heavy": { label: "Heavy alcohol use", icd10: "F10.10" },
  "former-alcohol": { label: "Former alcohol use", icd10: "Z86.41" },
  "sedentary": { label: "Sedentary lifestyle", icd10: "Z72.3" },
  "obesity-bmi": { label: "BMI ≥ 30 (Obesity)", icd10: "E66.9" },
};
