import { useQuery } from "@tanstack/react-query";
import { useParams, useSearch } from "wouter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Pill, AlertTriangle, Activity, TestTube, Heart, Clock, Shield, CheckCircle, XCircle, Loader2 } from "lucide-react";

interface SharedHealthSummary {
  patientName: string;
  generatedAt: string;
  recordType: string;
  expiresAt: string;
  data: {
    medications: Array<{ name: string; dosage: string; frequency: string; purpose: string }>;
    conditions: Array<{ name: string; status: string; diagnosedDate: string }>;
    allergies: Array<{ allergen: string; reaction: string; severity: string }>;
    recentLabs: Array<{ test: string; value: string; date: string; status: string }>;
    vitals: {
      bloodPressure: string;
      heartRate: string;
      weight: string;
      lastUpdated: string;
    };
  };
  disclaimer: string;
}

export default function ShareViewer() {
  const params = useParams();
  const searchString = useSearch();
  const searchParams = new URLSearchParams(searchString);
  const shareId = params.shareId;
  const code = searchParams.get("code");

  const { data, isLoading, error } = useQuery<SharedHealthSummary>({
    queryKey: ["/api/quick-share/access", shareId, code],
    queryFn: async () => {
      const response = await fetch(`/api/quick-share/access/${shareId}?code=${code}`);
      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || "Failed to access shared records");
      }
      return response.json();
    },
    enabled: !!shareId && !!code,
    retry: false,
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center space-y-4">
          <Loader2 className="h-12 w-12 animate-spin mx-auto text-primary" />
          <p className="text-muted-foreground">Loading patient health summary...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-4">
        <Card className="max-w-md w-full">
          <CardContent className="pt-6">
            <div className="text-center space-y-4">
              <div className="w-16 h-16 mx-auto bg-destructive/10 rounded-full flex items-center justify-center">
                <XCircle className="h-8 w-8 text-destructive" />
              </div>
              <h2 className="text-xl font-semibold">Unable to Access Records</h2>
              <p className="text-muted-foreground">
                {(error as Error)?.message || "This share link may have expired or is invalid."}
              </p>
              <p className="text-sm text-muted-foreground">
                Please ask the patient to generate a new share link.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  const expiryDate = new Date(data.expiresAt);
  const isExpiringSoon = expiryDate.getTime() - Date.now() < 60 * 60 * 1000;

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto p-4 md:p-6 max-w-4xl space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold">Patient Health Summary</h1>
            <p className="text-muted-foreground">Shared via Tabula Medica</p>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="flex items-center gap-1">
              <Shield className="h-3 w-3" />
              Verified
            </Badge>
            <Badge 
              variant={isExpiringSoon ? "destructive" : "secondary"} 
              className="flex items-center gap-1"
            >
              <Clock className="h-3 w-3" />
              {isExpiringSoon ? "Expiring Soon" : "Valid"}
            </Badge>
          </div>
        </div>

        <Alert>
          <CheckCircle className="h-4 w-4" />
          <AlertTitle>Verified Patient Share</AlertTitle>
          <AlertDescription>
            This health summary was generated by the patient on {new Date(data.generatedAt).toLocaleDateString()} 
            and expires on {expiryDate.toLocaleDateString()} at {expiryDate.toLocaleTimeString()}.
          </AlertDescription>
        </Alert>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Pill className="h-5 w-5 text-blue-500" />
                Current Medications
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {data.data.medications.map((med, idx) => (
                <div key={idx} className="p-3 bg-muted/50 rounded-lg">
                  <div className="font-medium">{med.name} {med.dosage}</div>
                  <div className="text-sm text-muted-foreground">{med.frequency}</div>
                  <Badge variant="outline" className="mt-1">{med.purpose}</Badge>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-5 w-5 text-green-500" />
                Active Conditions
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {data.data.conditions.map((cond, idx) => (
                <div key={idx} className="p-3 bg-muted/50 rounded-lg">
                  <div className="font-medium">{cond.name}</div>
                  <div className="flex items-center gap-2 mt-1">
                    <Badge variant={cond.status === "Active" ? "default" : "secondary"}>
                      {cond.status}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      Since {new Date(cond.diagnosedDate).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        <Card className="border-destructive/50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-destructive">
              <AlertTriangle className="h-5 w-5" />
              Allergies
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {data.data.allergies.map((allergy, idx) => (
                <div key={idx} className="p-3 bg-destructive/10 rounded-lg border border-destructive/20">
                  <div className="font-medium text-destructive">{allergy.allergen}</div>
                  <div className="text-sm text-muted-foreground">
                    {allergy.reaction} • {allergy.severity} severity
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TestTube className="h-5 w-5 text-purple-500" />
                Recent Lab Results
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {data.data.recentLabs.map((lab, idx) => (
                <div key={idx} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                  <div>
                    <div className="font-medium">{lab.test}</div>
                    <div className="text-xs text-muted-foreground">{lab.date}</div>
                  </div>
                  <div className="text-right">
                    <div className="font-mono font-bold">{lab.value}</div>
                    <Badge variant={lab.status === "Normal" ? "outline" : "secondary"} className="text-xs">
                      {lab.status}
                    </Badge>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Heart className="h-5 w-5 text-red-500" />
                Current Vitals
              </CardTitle>
              <CardDescription>Last updated: {data.data.vitals.lastUpdated}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div className="p-3 bg-muted/50 rounded-lg text-center">
                  <div className="text-xs text-muted-foreground">Blood Pressure</div>
                  <div className="font-mono font-bold">{data.data.vitals.bloodPressure}</div>
                </div>
                <div className="p-3 bg-muted/50 rounded-lg text-center">
                  <div className="text-xs text-muted-foreground">Heart Rate</div>
                  <div className="font-mono font-bold">{data.data.vitals.heartRate}</div>
                </div>
                <div className="p-3 bg-muted/50 rounded-lg text-center col-span-2">
                  <div className="text-xs text-muted-foreground">Weight</div>
                  <div className="font-mono font-bold">{data.data.vitals.weight}</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <Separator />

        <div className="text-center text-sm text-muted-foreground space-y-2">
          <p className="font-medium">{data.disclaimer}</p>
          <p>
            Powered by <span className="font-semibold">Tabula Medica</span> • 
            HIPAA-Compliant • Patient-Controlled Health Records
          </p>
        </div>
      </div>
    </div>
  );
}
