import { Router, Request, Response } from "express";
import { aiJourneySummaryService, JourneyDataInput } from "../services/ai-journey-summary-service";

const router = Router();

router.get("/metadata", (_req: Request, res: Response) => {
  res.json({
    service: "AI Journey Summary Generator",
    version: "1.0.0",
    features: [
      "Natural language health summaries",
      "3-6 month overview generation",
      "HEDIS metrics integration",
      "Specialist-shareable format"
    ],
    compliance: ["NO-CDS", "HIPAA PHI handling"],
    model: "gpt-5.2"
  });
});

router.post("/generate", async (req: Request, res: Response) => {
  try {
    const data: JourneyDataInput = req.body;
    
    if (!data.patientId || !data.dateRange) {
      return res.status(400).json({ 
        error: "Missing required fields: patientId, dateRange" 
      });
    }

    console.log(`[AIJourneySummary] Generating summary for patient ${data.patientId}`);
    console.log(`[HIPAA-AUDIT][AIJourneySummary] Summary generation requested for patient ${data.patientId}`);

    const summary = await aiJourneySummaryService.generateSummary(data);
    
    res.json(summary);
  } catch (error) {
    console.error("[AIJourneySummary] Generate error:", error);
    res.status(500).json({ error: "Failed to generate summary" });
  }
});

router.get("/sample", async (_req: Request, res: Response) => {
  try {
    const sampleData = aiJourneySummaryService.getSampleData();
    console.log("[AIJourneySummary] Generating sample summary");
    
    const summary = await aiJourneySummaryService.generateSummary(sampleData);
    
    res.json({
      inputData: sampleData,
      summary
    });
  } catch (error) {
    console.error("[AIJourneySummary] Sample error:", error);
    res.status(500).json({ error: "Failed to generate sample summary" });
  }
});

router.post("/format-shareable", (req: Request, res: Response) => {
  try {
    const { summary, format } = req.body;
    
    if (!summary) {
      return res.status(400).json({ error: "Missing summary data" });
    }

    let formatted: string;
    
    switch (format) {
      case "plain":
        formatted = summary.shareableVersion || summary.summary;
        break;
      case "markdown":
        formatted = formatAsMarkdown(summary);
        break;
      case "html":
        formatted = formatAsHTML(summary);
        break;
      default:
        formatted = summary.shareableVersion || summary.summary;
    }

    res.json({ formatted, format: format || "plain" });
  } catch (error) {
    console.error("[AIJourneySummary] Format error:", error);
    res.status(500).json({ error: "Failed to format summary" });
  }
});

function formatAsMarkdown(summary: any): string {
  let md = `# Patient Health Summary\n`;
  md += `**Period:** ${summary.dateRange?.start || "N/A"} to ${summary.dateRange?.end || "N/A"}\n\n`;
  md += `## Overview\n${summary.summary}\n\n`;
  
  if (summary.keyHighlights?.length > 0) {
    md += `## Key Highlights\n`;
    summary.keyHighlights.forEach((h: string) => {
      md += `- ${h}\n`;
    });
    md += "\n";
  }

  if (summary.healthTrends?.length > 0) {
    md += `## Health Trends\n`;
    summary.healthTrends.forEach((t: string) => {
      md += `- ${t}\n`;
    });
    md += "\n";
  }

  if (summary.specialistNotes) {
    md += `## Notes for Specialist\n${summary.specialistNotes}\n\n`;
  }

  md += `---\n*Generated by Tabula Medica | For informational purposes only*`;
  return md;
}

function formatAsHTML(summary: any): string {
  let html = `<div class="health-summary">`;
  html += `<h1>Patient Health Summary</h1>`;
  html += `<p><strong>Period:</strong> ${summary.dateRange?.start || "N/A"} to ${summary.dateRange?.end || "N/A"}</p>`;
  html += `<h2>Overview</h2><p>${summary.summary}</p>`;
  
  if (summary.keyHighlights?.length > 0) {
    html += `<h2>Key Highlights</h2><ul>`;
    summary.keyHighlights.forEach((h: string) => {
      html += `<li>${h}</li>`;
    });
    html += `</ul>`;
  }

  if (summary.healthTrends?.length > 0) {
    html += `<h2>Health Trends</h2><ul>`;
    summary.healthTrends.forEach((t: string) => {
      html += `<li>${t}</li>`;
    });
    html += `</ul>`;
  }

  if (summary.specialistNotes) {
    html += `<h2>Notes for Specialist</h2><p>${summary.specialistNotes}</p>`;
  }

  html += `<hr/><p><em>Generated by Tabula Medica | For informational purposes only</em></p>`;
  html += `</div>`;
  return html;
}

export function registerAIJourneySummaryRoutes(app: any): void {
  app.use("/api/ai-journey-summary", router);
  console.log("[Routes] AI Journey Summary routes registered at /api/ai-journey-summary/*");
}
