import type { Express, Request, Response } from "express";
import { generatePhiSafeText } from "./services/ai-gateway";

const SAFETY_DISCLAIMER = "AI-GENERATED SAFETY ANALYSIS - FOR CLINICAL REVIEW ONLY. This analysis is generated by AI and does not constitute clinical decision support. All findings must be independently verified by a licensed healthcare provider and pharmacist before any clinical action. Drug interaction data may not be exhaustive.";

interface PatientData {
  patientId: string;
  patientName?: string;
  age?: number;
  sex?: string;
  weight?: string;
  conditions: { name: string; status: string; onsetDate?: string; severity?: string; icdCode?: string }[];
  vitals: { type: string; value: string; unit: string; date?: string; status?: string }[];
  medications: { name: string; dosage: string; frequency: string; startDate?: string; drugClass?: string }[];
  allergies: string[];
  treatmentEfficacy?: { treatment: string; metric: string; currentValue: number; targetValue: number; trend: string; adherence: number }[];
  recentLabs?: { name: string; value: string; unit: string; referenceRange?: string; flag?: string; date?: string }[];
  genomics?: { gene: string; variant: string; phenotype: string; clinicalSignificance?: string }[];
}

const samplePatients: Record<string, PatientData> = {
  "PT-2024-001": {
    patientId: "PT-2024-001",
    patientName: "James Mitchell",
    age: 58,
    sex: "Male",
    weight: "198 lbs",
    conditions: [
      { name: "Type 2 Diabetes Mellitus", status: "active", onsetDate: "2022-03-15", severity: "moderate", icdCode: "E11.65" },
      { name: "Essential Hypertension", status: "active", onsetDate: "2020-08-10", severity: "mild", icdCode: "I10" },
      { name: "Hyperlipidemia", status: "active", onsetDate: "2021-06-22", icdCode: "E78.5" },
    ],
    vitals: [
      { type: "Blood Pressure", value: "138/86", unit: "mmHg", date: "2026-02-21", status: "elevated" },
      { type: "Heart Rate", value: "76", unit: "bpm", date: "2026-02-21", status: "normal" },
      { type: "Temperature", value: "98.4", unit: "°F", date: "2026-02-21", status: "normal" },
      { type: "Weight", value: "198", unit: "lbs", date: "2026-02-21" },
      { type: "BMI", value: "28.5", unit: "kg/m²", date: "2026-02-21", status: "overweight" },
      { type: "SpO2", value: "98", unit: "%", date: "2026-02-21", status: "normal" },
    ],
    medications: [
      { name: "Metformin", dosage: "1000mg", frequency: "twice daily", startDate: "2022-04-01", drugClass: "Biguanide" },
      { name: "Lisinopril", dosage: "10mg", frequency: "once daily", startDate: "2020-09-15", drugClass: "ACE Inhibitor" },
      { name: "Atorvastatin", dosage: "20mg", frequency: "once daily at bedtime", startDate: "2021-07-10", drugClass: "HMG-CoA Reductase Inhibitor" },
    ],
    allergies: ["Sulfa drugs", "Shellfish"],
    treatmentEfficacy: [
      { treatment: "Metformin 1000mg", metric: "HbA1c", currentValue: 7.2, targetValue: 6.5, trend: "improving", adherence: 88 },
      { treatment: "Lisinopril 10mg", metric: "Systolic BP", currentValue: 138, targetValue: 120, trend: "stable", adherence: 92 },
      { treatment: "Atorvastatin 20mg", metric: "LDL Cholesterol", currentValue: 128, targetValue: 100, trend: "improving", adherence: 85 },
    ],
    recentLabs: [
      { name: "HbA1c", value: "7.2", unit: "%", referenceRange: "4.0-5.6", flag: "high", date: "2026-02-10" },
      { name: "Fasting Glucose", value: "142", unit: "mg/dL", referenceRange: "70-100", flag: "high", date: "2026-02-10" },
      { name: "Total Cholesterol", value: "218", unit: "mg/dL", referenceRange: "<200", flag: "high", date: "2026-02-10" },
      { name: "LDL", value: "128", unit: "mg/dL", referenceRange: "<100", flag: "high", date: "2026-02-10" },
      { name: "HDL", value: "45", unit: "mg/dL", referenceRange: ">40", flag: "normal", date: "2026-02-10" },
      { name: "Triglycerides", value: "168", unit: "mg/dL", referenceRange: "<150", flag: "high", date: "2026-02-10" },
      { name: "Creatinine", value: "1.1", unit: "mg/dL", referenceRange: "0.7-1.3", flag: "normal", date: "2026-02-10" },
      { name: "eGFR", value: "78", unit: "mL/min", referenceRange: ">60", flag: "normal", date: "2026-02-10" },
      { name: "Microalbumin/Creatinine", value: "45", unit: "mg/g", referenceRange: "<30", flag: "high", date: "2026-02-10" },
      { name: "ALT", value: "32", unit: "U/L", referenceRange: "7-56", flag: "normal", date: "2026-02-10" },
      { name: "AST", value: "28", unit: "U/L", referenceRange: "10-40", flag: "normal", date: "2026-02-10" },
    ],
    genomics: [
      { gene: "CYP2C19", variant: "*1/*2", phenotype: "Intermediate Metabolizer", clinicalSignificance: "May affect metabolism of certain medications including clopidogrel" },
      { gene: "SLCO1B1", variant: "*1/*5", phenotype: "Intermediate Function", clinicalSignificance: "Increased risk of statin-related myopathy with high-dose simvastatin" },
    ],
  },
  "PT-2024-002": {
    patientId: "PT-2024-002",
    patientName: "Sarah Chen",
    age: 45,
    sex: "Female",
    weight: "135 lbs",
    conditions: [
      { name: "Generalized Anxiety Disorder", status: "active", onsetDate: "2019-05-20", severity: "moderate", icdCode: "F41.1" },
      { name: "Chronic Migraine", status: "active", onsetDate: "2018-01-10", severity: "moderate", icdCode: "G43.709" },
      { name: "Iron Deficiency Anemia", status: "active", onsetDate: "2025-08-15", severity: "mild", icdCode: "D50.9" },
    ],
    vitals: [
      { type: "Blood Pressure", value: "118/74", unit: "mmHg", date: "2026-02-21", status: "normal" },
      { type: "Heart Rate", value: "82", unit: "bpm", date: "2026-02-21", status: "normal" },
      { type: "Temperature", value: "98.6", unit: "°F", date: "2026-02-21", status: "normal" },
      { type: "Weight", value: "135", unit: "lbs", date: "2026-02-21" },
      { type: "BMI", value: "23.1", unit: "kg/m²", date: "2026-02-21", status: "normal" },
    ],
    medications: [
      { name: "Sertraline", dosage: "100mg", frequency: "once daily", startDate: "2019-06-01", drugClass: "SSRI" },
      { name: "Sumatriptan", dosage: "50mg", frequency: "as needed for migraines", startDate: "2018-02-15", drugClass: "Triptan" },
      { name: "Ferrous Sulfate", dosage: "325mg", frequency: "once daily", startDate: "2025-09-01", drugClass: "Iron Supplement" },
    ],
    allergies: ["Penicillin", "Latex"],
    treatmentEfficacy: [
      { treatment: "Sertraline 100mg", metric: "GAD-7 Score", currentValue: 8, targetValue: 5, trend: "improving", adherence: 95 },
      { treatment: "Sumatriptan 50mg", metric: "Migraine Days/Month", currentValue: 6, targetValue: 4, trend: "stable", adherence: 78 },
      { treatment: "Ferrous Sulfate 325mg", metric: "Hemoglobin", currentValue: 11.8, targetValue: 12.5, trend: "improving", adherence: 90 },
    ],
    recentLabs: [
      { name: "Hemoglobin", value: "11.8", unit: "g/dL", referenceRange: "12.0-16.0", flag: "low", date: "2026-02-05" },
      { name: "Ferritin", value: "18", unit: "ng/mL", referenceRange: "20-200", flag: "low", date: "2026-02-05" },
      { name: "Iron", value: "45", unit: "mcg/dL", referenceRange: "60-170", flag: "low", date: "2026-02-05" },
      { name: "TIBC", value: "420", unit: "mcg/dL", referenceRange: "250-370", flag: "high", date: "2026-02-05" },
      { name: "TSH", value: "2.4", unit: "mIU/L", referenceRange: "0.4-4.0", flag: "normal", date: "2026-02-05" },
      { name: "Serotonin", value: "185", unit: "ng/mL", referenceRange: "101-283", flag: "normal", date: "2026-02-05" },
    ],
    genomics: [
      { gene: "CYP2D6", variant: "*1/*4", phenotype: "Intermediate Metabolizer", clinicalSignificance: "May require dose adjustment for certain SSRIs and triptans" },
    ],
  },
  "PT-2024-003": {
    patientId: "PT-2024-003",
    patientName: "Robert Johnson",
    age: 72,
    sex: "Male",
    weight: "210 lbs",
    conditions: [
      { name: "Congestive Heart Failure (NYHA Class II)", status: "active", onsetDate: "2023-02-10", severity: "moderate", icdCode: "I50.22" },
      { name: "Atrial Fibrillation", status: "active", onsetDate: "2023-02-10", severity: "moderate", icdCode: "I48.91" },
      { name: "Chronic Kidney Disease Stage 3a", status: "active", onsetDate: "2024-01-20", severity: "moderate", icdCode: "N18.31" },
      { name: "Type 2 Diabetes Mellitus", status: "active", onsetDate: "2015-06-10", icdCode: "E11.65" },
    ],
    vitals: [
      { type: "Blood Pressure", value: "142/88", unit: "mmHg", date: "2026-02-21", status: "elevated" },
      { type: "Heart Rate", value: "88", unit: "bpm (irregular)", date: "2026-02-21", status: "irregular" },
      { type: "Temperature", value: "98.2", unit: "°F", date: "2026-02-21", status: "normal" },
      { type: "Weight", value: "210", unit: "lbs", date: "2026-02-21" },
      { type: "SpO2", value: "94", unit: "%", date: "2026-02-21", status: "borderline" },
    ],
    medications: [
      { name: "Furosemide", dosage: "40mg", frequency: "once daily", startDate: "2023-03-01", drugClass: "Loop Diuretic" },
      { name: "Carvedilol", dosage: "12.5mg", frequency: "twice daily", startDate: "2023-03-01", drugClass: "Beta Blocker" },
      { name: "Apixaban", dosage: "5mg", frequency: "twice daily", startDate: "2023-03-15", drugClass: "Direct Oral Anticoagulant" },
      { name: "Metformin", dosage: "500mg", frequency: "twice daily", startDate: "2015-07-01", drugClass: "Biguanide" },
      { name: "Lisinopril", dosage: "20mg", frequency: "once daily", startDate: "2023-03-01", drugClass: "ACE Inhibitor" },
    ],
    allergies: ["Aspirin", "Codeine"],
    treatmentEfficacy: [
      { treatment: "Furosemide 40mg", metric: "Weight (fluid)", currentValue: 210, targetValue: 200, trend: "worsening", adherence: 80 },
      { treatment: "Carvedilol 12.5mg", metric: "Heart Rate", currentValue: 88, targetValue: 70, trend: "stable", adherence: 85 },
      { treatment: "Apixaban 5mg", metric: "INR Equivalent", currentValue: 2.1, targetValue: 2.5, trend: "stable", adherence: 92 },
    ],
    recentLabs: [
      { name: "BNP", value: "485", unit: "pg/mL", referenceRange: "<100", flag: "high", date: "2026-02-15" },
      { name: "Creatinine", value: "1.6", unit: "mg/dL", referenceRange: "0.7-1.3", flag: "high", date: "2026-02-15" },
      { name: "eGFR", value: "48", unit: "mL/min", referenceRange: ">60", flag: "low", date: "2026-02-15" },
      { name: "Potassium", value: "4.8", unit: "mEq/L", referenceRange: "3.5-5.0", flag: "normal", date: "2026-02-15" },
      { name: "Sodium", value: "138", unit: "mEq/L", referenceRange: "136-145", flag: "normal", date: "2026-02-15" },
      { name: "HbA1c", value: "7.8", unit: "%", referenceRange: "4.0-5.6", flag: "high", date: "2026-02-15" },
      { name: "Lactic Acid", value: "2.8", unit: "mmol/L", referenceRange: "0.5-2.2", flag: "high", date: "2026-02-15" },
    ],
    genomics: [
      { gene: "CYP2C9", variant: "*1/*3", phenotype: "Intermediate Metabolizer", clinicalSignificance: "Reduced warfarin clearance; relevant if switching anticoagulants" },
      { gene: "VKORC1", variant: "-1639G>A (AG)", phenotype: "Intermediate Sensitivity", clinicalSignificance: "Moderate warfarin sensitivity if warfarin is considered" },
    ],
  },
};

function buildDrugInteractionKnowledgeBase(patient: PatientData) {
  const interactions: any[] = [];
  const meds = patient.medications.map(m => m.name.toLowerCase());

  if (meds.includes("metformin") && patient.recentLabs?.some(l => l.name === "eGFR" && parseFloat(l.value) < 60)) {
    interactions.push({
      id: `di-${patient.patientId}-met-ckd`,
      type: "contraindication",
      severity: "high",
      title: "Metformin with Reduced Renal Function",
      drugs: ["Metformin"],
      condition: "Reduced eGFR",
      description: "Metformin requires dose adjustment or discontinuation when eGFR is below 30 mL/min. Use with caution between 30-45 mL/min. Current eGFR may warrant reassessment.",
      labValue: patient.recentLabs?.find(l => l.name === "eGFR")?.value,
      recommendation: "Review metformin dosing per current renal function guidelines",
      evidence: "FDA labeling update 2016; KDIGO guidelines",
    });
  }

  if (meds.includes("metformin") && patient.recentLabs?.some(l => l.name === "Lactic Acid" && parseFloat(l.value) > 2.0)) {
    interactions.push({
      id: `di-${patient.patientId}-met-lac`,
      type: "high_risk_alert",
      severity: "critical",
      title: "Elevated Lactic Acid with Metformin Use",
      drugs: ["Metformin"],
      condition: "Elevated Lactic Acid",
      description: "Lactic acidosis is a rare but serious complication of metformin. Elevated lactic acid levels require immediate attention.",
      labValue: patient.recentLabs?.find(l => l.name === "Lactic Acid")?.value,
      recommendation: "Assess for signs/symptoms of lactic acidosis; consider holding metformin pending evaluation",
      evidence: "FDA Black Box Warning",
    });
  }

  if (meds.includes("lisinopril") && meds.includes("furosemide")) {
    interactions.push({
      id: `di-${patient.patientId}-ace-loop`,
      type: "drug_interaction",
      severity: "moderate",
      title: "ACE Inhibitor + Loop Diuretic Interaction",
      drugs: ["Lisinopril", "Furosemide"],
      description: "Concurrent use may cause excessive hypotension, especially upon initiation. Monitor blood pressure closely and watch for renal function changes.",
      recommendation: "Monitor BP, electrolytes, and renal function regularly",
      evidence: "Clinical pharmacology reference",
    });
  }

  if (meds.includes("lisinopril") && patient.recentLabs?.some(l => l.name === "Potassium" && parseFloat(l.value) > 4.5)) {
    interactions.push({
      id: `di-${patient.patientId}-ace-k`,
      type: "high_risk_alert",
      severity: "moderate",
      title: "ACE Inhibitor with Borderline Potassium",
      drugs: ["Lisinopril"],
      condition: "Borderline Hyperkalemia Risk",
      description: "ACE inhibitors can increase serum potassium. Current potassium is at the upper normal range. Combined with renal impairment, risk of hyperkalemia is elevated.",
      labValue: patient.recentLabs?.find(l => l.name === "Potassium")?.value,
      recommendation: "Monitor potassium levels closely; consider dietary potassium counseling",
      evidence: "AHA/ACC Heart Failure Guidelines",
    });
  }

  if (meds.includes("sertraline") && meds.includes("sumatriptan")) {
    interactions.push({
      id: `di-${patient.patientId}-ssri-trip`,
      type: "drug_interaction",
      severity: "moderate",
      title: "SSRI + Triptan: Serotonin Syndrome Risk",
      drugs: ["Sertraline", "Sumatriptan"],
      description: "Concurrent use of SSRIs and triptans may increase the risk of serotonin syndrome. Monitor for symptoms including agitation, confusion, tachycardia, and neuromuscular changes.",
      recommendation: "Educate patient on serotonin syndrome symptoms; use lowest effective triptan dose",
      evidence: "FDA Drug Safety Communication 2006 (updated)",
    });
  }

  if (meds.includes("atorvastatin") && patient.genomics?.some(g => g.gene === "SLCO1B1" && g.variant.includes("*5"))) {
    interactions.push({
      id: `di-${patient.patientId}-statin-slco`,
      type: "pharmacogenomic_alert",
      severity: "moderate",
      title: "SLCO1B1 Variant: Statin Myopathy Risk",
      drugs: ["Atorvastatin"],
      genomicData: patient.genomics?.find(g => g.gene === "SLCO1B1"),
      description: "SLCO1B1*5 variant is associated with increased risk of statin-related myopathy. While atorvastatin risk is lower than simvastatin, monitoring is recommended.",
      recommendation: "Monitor for muscle pain/weakness; consider CK level if symptomatic; avoid switching to simvastatin",
      evidence: "CPIC Guideline for Statins and SLCO1B1",
    });
  }

  if (meds.includes("apixaban") && patient.recentLabs?.some(l => l.name === "Creatinine" && parseFloat(l.value) > 1.5)) {
    interactions.push({
      id: `di-${patient.patientId}-apix-ckd`,
      type: "contraindication",
      severity: "moderate",
      title: "Apixaban Dose Assessment with Renal Impairment",
      drugs: ["Apixaban"],
      condition: "Reduced Renal Function",
      description: "Apixaban dose may need adjustment in patients with renal impairment. Consider age, weight, and creatinine when determining appropriate dose.",
      labValue: patient.recentLabs?.find(l => l.name === "Creatinine")?.value,
      recommendation: "Verify dose is appropriate per renal dosing criteria (age ≥80, weight ≤60kg, or Cr ≥1.5)",
      evidence: "Apixaban prescribing information",
    });
  }

  if (meds.includes("carvedilol") && patient.conditions.some(c => c.name.toLowerCase().includes("heart failure"))) {
    const hr = patient.vitals.find(v => v.type === "Heart Rate");
    if (hr && parseInt(hr.value) > 80) {
      interactions.push({
        id: `di-${patient.patientId}-carv-hr`,
        type: "high_risk_alert",
        severity: "low",
        title: "Suboptimal Heart Rate Control in Heart Failure",
        drugs: ["Carvedilol"],
        condition: "Heart Failure with Elevated HR",
        description: "Target heart rate in heart failure is typically 60-70 bpm. Current heart rate suggests possible need for dose optimization.",
        vitalValue: hr.value,
        recommendation: "Consider uptitrating carvedilol if tolerated and BP allows",
        evidence: "ACC/AHA Heart Failure Guidelines",
      });
    }
  }

  const allergyDrugMap: Record<string, string[]> = {
    "sulfa drugs": ["sulfamethoxazole", "sulfasalazine", "furosemide", "thiazide"],
    "aspirin": ["aspirin", "ketorolac", "ibuprofen"],
    "penicillin": ["amoxicillin", "ampicillin", "piperacillin"],
    "codeine": ["codeine", "tramadol", "hydrocodone"],
  };

  for (const allergy of patient.allergies) {
    const relatedDrugs = allergyDrugMap[allergy.toLowerCase()] || [];
    for (const med of patient.medications) {
      if (relatedDrugs.some(rd => med.name.toLowerCase().includes(rd))) {
        interactions.push({
          id: `di-${patient.patientId}-allergy-${med.name.toLowerCase()}`,
          type: "allergy_alert",
          severity: "high",
          title: `Potential Cross-Reactivity: ${allergy} Allergy with ${med.name}`,
          drugs: [med.name],
          allergen: allergy,
          description: `Patient has documented ${allergy} allergy. ${med.name} may have cross-reactivity potential. Review allergy documentation and assess risk.`,
          recommendation: "Verify allergy history specifics; assess benefit-risk ratio",
          evidence: "Clinical pharmacology cross-reactivity data",
        });
      }
    }
  }

  return interactions;
}

function linkLabsToConditions(patient: PatientData) {
  const links: any[] = [];
  const conditionNames = patient.conditions.map(c => c.name.toLowerCase());

  const labConditionMap: Record<string, { conditions: string[]; relevance: string }> = {
    "HbA1c": { conditions: ["diabetes"], relevance: "Primary monitoring marker for glycemic control" },
    "Fasting Glucose": { conditions: ["diabetes"], relevance: "Indicates current blood sugar status" },
    "Total Cholesterol": { conditions: ["hyperlipidemia", "heart"], relevance: "Cardiovascular risk marker" },
    "LDL": { conditions: ["hyperlipidemia", "heart"], relevance: "Primary target for lipid-lowering therapy" },
    "HDL": { conditions: ["hyperlipidemia", "heart"], relevance: "Protective cardiovascular marker" },
    "Triglycerides": { conditions: ["hyperlipidemia", "diabetes"], relevance: "Metabolic syndrome component" },
    "Creatinine": { conditions: ["kidney", "heart failure"], relevance: "Renal function marker" },
    "eGFR": { conditions: ["kidney", "diabetes"], relevance: "Estimated glomerular filtration rate - kidney function" },
    "Microalbumin/Creatinine": { conditions: ["diabetes", "kidney", "hypertension"], relevance: "Early diabetic nephropathy marker" },
    "BNP": { conditions: ["heart failure"], relevance: "Heart failure severity and monitoring marker" },
    "Potassium": { conditions: ["kidney", "heart"], relevance: "Electrolyte affected by cardiac and renal medications" },
    "Sodium": { conditions: ["heart failure", "kidney"], relevance: "Hyponatremia monitoring in heart failure" },
    "Hemoglobin": { conditions: ["anemia"], relevance: "Primary marker for anemia severity" },
    "Ferritin": { conditions: ["anemia", "iron"], relevance: "Iron stores assessment" },
    "Iron": { conditions: ["anemia", "iron"], relevance: "Serum iron level" },
    "TIBC": { conditions: ["anemia", "iron"], relevance: "Total iron binding capacity - iron deficiency marker" },
    "TSH": { conditions: ["thyroid", "anxiety", "fatigue"], relevance: "Thyroid function screening" },
    "ALT": { conditions: ["liver", "diabetes"], relevance: "Liver function - important for statin monitoring" },
    "AST": { conditions: ["liver", "heart"], relevance: "Liver and cardiac tissue marker" },
    "Lactic Acid": { conditions: ["diabetes", "kidney", "heart failure"], relevance: "Tissue oxygenation and metformin safety marker" },
    "Serotonin": { conditions: ["anxiety", "depression", "migraine"], relevance: "Neurotransmitter level relevant to SSRI therapy" },
  };

  const vitalConditionMap: Record<string, { conditions: string[]; relevance: string }> = {
    "Blood Pressure": { conditions: ["hypertension", "heart failure", "kidney", "diabetes"], relevance: "Cardiovascular and renal risk marker" },
    "Heart Rate": { conditions: ["heart failure", "atrial fibrillation", "anxiety"], relevance: "Cardiac rhythm and rate control" },
    "SpO2": { conditions: ["heart failure", "pulmonary"], relevance: "Oxygen saturation - cardiopulmonary status" },
    "BMI": { conditions: ["diabetes", "hypertension", "hyperlipidemia"], relevance: "Metabolic syndrome component" },
    "Weight": { conditions: ["heart failure", "diabetes"], relevance: "Fluid status in heart failure; weight management in diabetes" },
    "Temperature": { conditions: ["infection"], relevance: "Infection screening" },
  };

  for (const lab of patient.recentLabs || []) {
    const mapping = labConditionMap[lab.name];
    if (mapping) {
      const linkedConditions = patient.conditions.filter(c =>
        mapping.conditions.some(mc => c.name.toLowerCase().includes(mc))
      );
      if (linkedConditions.length > 0) {
        links.push({
          type: "lab",
          labName: lab.name,
          value: lab.value,
          unit: lab.unit,
          referenceRange: lab.referenceRange,
          flag: lab.flag,
          date: lab.date,
          linkedConditions: linkedConditions.map(c => ({
            name: c.name,
            icdCode: c.icdCode,
            status: c.status,
          })),
          relevance: mapping.relevance,
          isAbnormal: lab.flag && lab.flag !== "normal",
          linkedMedications: patient.medications.filter(m => {
            const tx = patient.treatmentEfficacy?.find(t =>
              t.treatment.toLowerCase().includes(m.name.toLowerCase()) && t.metric === lab.name
            );
            return !!tx;
          }).map(m => ({
            name: m.name,
            dosage: m.dosage,
            efficacy: patient.treatmentEfficacy?.find(t =>
              t.treatment.toLowerCase().includes(m.name.toLowerCase()) && t.metric === lab.name
            ),
          })),
        });
      }
    }
  }

  for (const vital of patient.vitals) {
    const mapping = vitalConditionMap[vital.type];
    if (mapping) {
      const linkedConditions = patient.conditions.filter(c =>
        mapping.conditions.some(mc => c.name.toLowerCase().includes(mc))
      );
      if (linkedConditions.length > 0) {
        links.push({
          type: "vital",
          vitalType: vital.type,
          value: vital.value,
          unit: vital.unit,
          status: vital.status,
          date: vital.date,
          linkedConditions: linkedConditions.map(c => ({
            name: c.name,
            icdCode: c.icdCode,
            status: c.status,
          })),
          relevance: mapping.relevance,
          isAbnormal: vital.status && vital.status !== "normal",
          linkedMedications: patient.medications.filter(m => {
            const tx = patient.treatmentEfficacy?.find(t =>
              t.treatment.toLowerCase().includes(m.name.toLowerCase()) && t.metric.toLowerCase().includes(vital.type.toLowerCase().split(" ")[0])
            );
            return !!tx;
          }).map(m => ({
            name: m.name,
            dosage: m.dosage,
            efficacy: patient.treatmentEfficacy?.find(t =>
              t.treatment.toLowerCase().includes(m.name.toLowerCase())
            ),
          })),
        });
      }
    }
  }

  return links;
}

function computeRiskScore(patient: PatientData, interactions: any[]) {
  let score = 0;
  let factors: string[] = [];

  if (patient.age && patient.age >= 65) { score += 15; factors.push("Age ≥65"); }
  if (patient.medications.length >= 5) { score += 10; factors.push("Polypharmacy (≥5 medications)"); }

  const criticalInteractions = interactions.filter(i => i.severity === "critical");
  const highInteractions = interactions.filter(i => i.severity === "high");
  score += criticalInteractions.length * 25;
  score += highInteractions.length * 15;
  if (criticalInteractions.length > 0) factors.push(`${criticalInteractions.length} critical alert(s)`);
  if (highInteractions.length > 0) factors.push(`${highInteractions.length} high-severity alert(s)`);

  const abnormalLabs = (patient.recentLabs || []).filter(l => l.flag && l.flag !== "normal");
  score += abnormalLabs.length * 3;
  if (abnormalLabs.length >= 3) factors.push(`${abnormalLabs.length} abnormal lab values`);

  const worseningTx = (patient.treatmentEfficacy || []).filter(t => t.trend === "worsening");
  score += worseningTx.length * 10;
  if (worseningTx.length > 0) factors.push(`${worseningTx.length} worsening treatment trend(s)`);

  const lowAdherence = (patient.treatmentEfficacy || []).filter(t => t.adherence < 80);
  score += lowAdherence.length * 8;
  if (lowAdherence.length > 0) factors.push("Low medication adherence detected");

  if (patient.conditions.length >= 3) { score += 5; factors.push("Multiple comorbidities"); }

  const hasRenal = patient.conditions.some(c => c.name.toLowerCase().includes("kidney"));
  const hasHF = patient.conditions.some(c => c.name.toLowerCase().includes("heart failure"));
  if (hasRenal) { score += 10; factors.push("Renal impairment present"); }
  if (hasHF) { score += 10; factors.push("Heart failure present"); }

  score = Math.min(score, 100);
  let level: string;
  if (score >= 70) level = "critical";
  else if (score >= 50) level = "high";
  else if (score >= 30) level = "moderate";
  else level = "low";

  return { score, level, factors, maxScore: 100 };
}

export function registerAISafetyAnalysisRoutes(app: Express) {
  app.get("/api/ai-safety/patients", (_req: Request, res: Response) => {
    try {
      const patients = Object.values(samplePatients).map(p => ({
        patientId: p.patientId,
        patientName: p.patientName,
        age: p.age,
        sex: p.sex,
        conditionCount: p.conditions.length,
        medicationCount: p.medications.length,
        hasGenomics: !!(p.genomics && p.genomics.length > 0),
      }));
      res.json({ success: true, data: patients });
    } catch (error) {
      console.error("[AISafety] Error fetching patients:", error);
      res.status(500).json({ success: false, error: "Failed to fetch patients" });
    }
  });

  app.get("/api/ai-safety/patient/:patientId", (req: Request, res: Response) => {
    try {
      const patient = samplePatients[req.params.patientId];
      if (!patient) {
        return res.status(404).json({ success: false, error: "Patient not found" });
      }
      res.json({ success: true, data: patient });
    } catch (error) {
      console.error("[AISafety] Error fetching patient:", error);
      res.status(500).json({ success: false, error: "Failed to fetch patient data" });
    }
  });

  app.post("/api/ai-safety/analyze", async (req: Request, res: Response) => {
    try {
      const { patientId } = req.body;
      if (!patientId) {
        return res.status(400).json({ success: false, error: "Patient ID is required" });
      }

      const patient = samplePatients[patientId];
      if (!patient) {
        return res.status(404).json({ success: false, error: "Patient not found" });
      }

      console.log(`[HIPAA-AUDIT] ${new Date().toISOString()} | Action: AI_SAFETY_ANALYSIS | Patient: ${patientId}`);

      const ruleBasedInteractions = buildDrugInteractionKnowledgeBase(patient);
      const conditionLinks = linkLabsToConditions(patient);
      const riskScore = computeRiskScore(patient, ruleBasedInteractions);

      try {
        const patientContext = `PATIENT: ${patient.patientName} (${patient.patientId}), Age ${patient.age}, ${patient.sex}
CONDITIONS: ${patient.conditions.map(c => `${c.name} (${c.status})`).join("; ")}
MEDICATIONS: ${patient.medications.map(m => `${m.name} ${m.dosage} ${m.frequency} [${m.drugClass || ""}]`).join("; ")}
ALLERGIES: ${patient.allergies.join(", ")}
LABS: ${(patient.recentLabs || []).map(l => `${l.name}: ${l.value} ${l.unit} ${l.flag !== "normal" ? `[${l.flag}]` : ""}`).join("; ")}
VITALS: ${patient.vitals.map(v => `${v.type}: ${v.value} ${v.unit} ${v.status !== "normal" ? `(${v.status})` : ""}`).join("; ")}
${patient.genomics ? `PHARMACOGENOMICS: ${patient.genomics.map(g => `${g.gene} ${g.variant} - ${g.phenotype}`).join("; ")}` : ""}
RULE-BASED ALERTS FOUND: ${ruleBasedInteractions.length}`;

        const content = await generatePhiSafeText({
          system: `You are a clinical pharmacology safety analysis assistant. Analyze the patient data and provide additional safety insights beyond the rule-based alerts already identified.

CRITICAL: This is for informational/documentation purposes ONLY. NOT clinical decision support. All findings require verification by licensed healthcare providers and pharmacists.

Return JSON with:
- "additionalInteractions": array of {title, drugs (array), severity (critical/high/moderate/low), description, recommendation, evidence} - any drug interactions or safety concerns NOT already captured by rule-based analysis
- "genomicInsights": array of {gene, clinicalImpact, affectedDrugs (array), recommendation} if genomic data is available
- "conditionSpecificRisks": array of {condition, risk, severity, description} - risks from condition combinations
- "monitoringRecommendations": array of {parameter, frequency, rationale, priority (urgent/routine)}
- "overallAssessment": brief narrative assessment of patient safety profile`,
          user: `Analyze this patient for drug interactions, contraindications, and safety alerts:\n\n${patientContext}`,
          responseMimeType: "application/json",
          maxTokens: 3000,
        });

        const aiAnalysis = JSON.parse(content || "{}");

        const allInteractions = [
          ...ruleBasedInteractions,
          ...(aiAnalysis.additionalInteractions || []).map((ai: any, idx: number) => ({
            ...ai,
            id: `ai-${patient.patientId}-${idx}`,
            type: "drug_interaction",
            source: "ai_analysis",
          })),
        ];

        res.json({
          success: true,
          data: {
            patientId,
            patientName: patient.patientName,
            analysisTimestamp: new Date().toISOString(),
            riskScore,
            interactions: allInteractions,
            conditionLinks,
            genomicInsights: aiAnalysis.genomicInsights || [],
            conditionSpecificRisks: aiAnalysis.conditionSpecificRisks || [],
            monitoringRecommendations: aiAnalysis.monitoringRecommendations || [],
            overallAssessment: aiAnalysis.overallAssessment || "",
            disclaimer: SAFETY_DISCLAIMER,
          },
        });
      } catch (aiError: any) {
        console.warn("[AISafety] AI analysis unavailable:", aiError.message);
        res.json({
          success: true,
          data: {
            patientId,
            patientName: patient.patientName,
            analysisTimestamp: new Date().toISOString(),
            riskScore,
            interactions: ruleBasedInteractions,
            conditionLinks,
            genomicInsights: (patient.genomics || []).map(g => ({
              gene: g.gene,
              clinicalImpact: g.clinicalSignificance,
              affectedDrugs: [],
              recommendation: "Consult pharmacogenomics reference for clinical guidance",
            })),
            conditionSpecificRisks: [],
            monitoringRecommendations: generateFallbackMonitoring(patient),
            overallAssessment: `${patient.patientName} has ${patient.conditions.length} active conditions on ${patient.medications.length} medications. ${ruleBasedInteractions.length} safety alerts identified requiring clinical review.`,
            disclaimer: SAFETY_DISCLAIMER,
          },
        });
      }
    } catch (error) {
      console.error("[AISafety] Analysis error:", error);
      res.status(500).json({ success: false, error: "Failed to perform safety analysis" });
    }
  });

  app.post("/api/ai-safety/condition-links", (req: Request, res: Response) => {
    try {
      const { patientId } = req.body;
      if (!patientId) {
        return res.status(400).json({ success: false, error: "Patient ID is required" });
      }

      const patient = samplePatients[patientId];
      if (!patient) {
        return res.status(404).json({ success: false, error: "Patient not found" });
      }

      console.log(`[HIPAA-AUDIT] ${new Date().toISOString()} | Action: CONDITION_LINK_ANALYSIS | Patient: ${patientId}`);

      const links = linkLabsToConditions(patient);
      const conditionSummaries = patient.conditions.map(c => {
        const relatedLinks = links.filter(l =>
          l.linkedConditions.some((lc: any) => lc.name === c.name)
        );
        const abnormalRelated = relatedLinks.filter(l => l.isAbnormal);
        return {
          condition: c.name,
          icdCode: c.icdCode,
          status: c.status,
          severity: c.severity,
          linkedLabCount: relatedLinks.filter(l => l.type === "lab").length,
          linkedVitalCount: relatedLinks.filter(l => l.type === "vital").length,
          abnormalCount: abnormalRelated.length,
          overallStatus: abnormalRelated.length >= 2 ? "needs_attention" : abnormalRelated.length === 1 ? "monitor" : "stable",
        };
      });

      res.json({
        success: true,
        data: {
          patientId,
          patientName: patient.patientName,
          links,
          conditionSummaries,
          generatedAt: new Date().toISOString(),
        },
      });
    } catch (error) {
      console.error("[AISafety] Condition link error:", error);
      res.status(500).json({ success: false, error: "Failed to generate condition links" });
    }
  });

  console.log("[Routes] AI Safety Analysis routes registered at /api/ai-safety/*");
}

function generateFallbackMonitoring(patient: PatientData) {
  const recs: any[] = [];

  if (patient.conditions.some(c => c.name.toLowerCase().includes("diabetes"))) {
    recs.push({ parameter: "HbA1c", frequency: "Every 3 months", rationale: "Glycemic control monitoring", priority: "routine" });
    recs.push({ parameter: "Renal Function Panel", frequency: "Every 6 months", rationale: "Diabetes nephropathy screening", priority: "routine" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("heart failure"))) {
    recs.push({ parameter: "BNP", frequency: "Every 3-6 months", rationale: "Heart failure severity monitoring", priority: "routine" });
    recs.push({ parameter: "Daily Weight", frequency: "Daily", rationale: "Fluid status monitoring", priority: "urgent" });
    recs.push({ parameter: "Electrolytes", frequency: "Monthly", rationale: "Diuretic and ACE inhibitor safety", priority: "routine" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("kidney"))) {
    recs.push({ parameter: "eGFR/Creatinine", frequency: "Every 3 months", rationale: "CKD progression monitoring", priority: "routine" });
    recs.push({ parameter: "Potassium", frequency: "Monthly", rationale: "Hyperkalemia risk with ACE inhibitors", priority: "urgent" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("anemia"))) {
    recs.push({ parameter: "CBC with Iron Studies", frequency: "Every 2-3 months", rationale: "Iron deficiency anemia response monitoring", priority: "routine" });
  }
  if (patient.medications.some(m => m.name.toLowerCase().includes("statin") || m.name.toLowerCase().includes("atorvastatin"))) {
    recs.push({ parameter: "Lipid Panel", frequency: "Every 6-12 months", rationale: "Statin efficacy monitoring", priority: "routine" });
    recs.push({ parameter: "Liver Function (ALT/AST)", frequency: "Annually", rationale: "Statin hepatotoxicity screening", priority: "routine" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("anxiety") || c.name.toLowerCase().includes("depression"))) {
    recs.push({ parameter: "GAD-7 / PHQ-9 Assessment", frequency: "Every 3 months", rationale: "Mental health symptom monitoring", priority: "routine" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("migraine"))) {
    recs.push({ parameter: "Migraine Diary Review", frequency: "Every visit", rationale: "Track frequency and treatment response", priority: "routine" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("hypertension"))) {
    recs.push({ parameter: "Blood Pressure", frequency: "Every visit / home monitoring", rationale: "Hypertension control assessment", priority: "routine" });
  }
  if (patient.conditions.some(c => c.name.toLowerCase().includes("atrial fibrillation"))) {
    recs.push({ parameter: "Heart Rate & Rhythm", frequency: "Every visit", rationale: "Rate/rhythm control monitoring", priority: "urgent" });
    recs.push({ parameter: "Anticoagulation Assessment", frequency: "Every 6 months", rationale: "Bleeding and thrombotic risk re-evaluation", priority: "routine" });
  }

  return recs;
}
