import type { Express, Request, Response } from "express";
import { logPhiAccess } from "./security/hipaa-audit";
import PDFDocument from "pdfkit";
import { Readable } from "stream";

interface PatientSummaryData {
  patientName: string;
  dateOfBirth: string;
  mrn: string;
  generatedDate: string;
  summary: {
    overallHealth: string;
    activeConditions: string[];
    currentMedications: { name: string; dose: string; frequency: string }[];
    allergies: string[];
    recentLabs: { name: string; value: string; date: string; status: string }[];
    recentVisits: { date: string; provider: string; reason: string; facility: string }[];
    immunizations: { name: string; date: string }[];
    upcomingAppointments: { date: string; provider: string; reason: string }[];
  };
  sources: { name: string; lastSynced: string }[];
  disclaimer: string;
}

const samplePatientSummary: PatientSummaryData = {
  patientName: "John Smith",
  dateOfBirth: "1957-05-15",
  mrn: "MRN-2025-001234",
  generatedDate: new Date().toISOString(),
  summary: {
    overallHealth: "Overall health status is stable with well-managed chronic conditions. Blood pressure has improved with current medication regimen. Metabolic markers remain within healthy ranges.",
    activeConditions: [
      "Essential Hypertension (Stage 1) - Diagnosed Sep 2025",
      "Hyperlipidemia - Managed",
    ],
    currentMedications: [
      { name: "Lisinopril", dose: "10mg", frequency: "Once daily" },
      { name: "Atorvastatin", dose: "20mg", frequency: "Once daily at bedtime" },
    ],
    allergies: [
      "Penicillin - Rash",
      "Sulfa drugs - Hives",
    ],
    recentLabs: [
      { name: "HbA1c", value: "5.4%", date: "2025-12-15", status: "Normal" },
      { name: "Total Cholesterol", value: "198 mg/dL", date: "2025-06-12", status: "Borderline" },
      { name: "LDL Cholesterol", value: "112 mg/dL", date: "2025-06-12", status: "Borderline" },
      { name: "HDL Cholesterol", value: "58 mg/dL", date: "2025-06-12", status: "Normal" },
      { name: "Blood Pressure", value: "128/82 mmHg", date: "2025-12-15", status: "Improved" },
    ],
    recentVisits: [
      { date: "2025-12-15", provider: "Dr. Sarah Chen", reason: "Annual Physical", facility: "Memorial Health Clinic" },
      { date: "2025-11-20", provider: "Dr. Michael Torres", reason: "Cardiology Consult", facility: "Downtown Cardiology" },
      { date: "2025-10-05", provider: "Dr. Lisa Wong", reason: "Chest X-Ray", facility: "Regional Medical Center" },
    ],
    immunizations: [
      { name: "Influenza (Flu) Vaccine", date: "2025-08-01" },
      { name: "COVID-19 Booster", date: "2025-01-15" },
      { name: "Tdap", date: "2023-03-20" },
      { name: "Pneumococcal (PPSV23)", date: "2022-05-10" },
    ],
    upcomingAppointments: [
      { date: "2026-03-15", provider: "Dr. Sarah Chen", reason: "Blood Pressure Follow-up" },
      { date: "2026-06-01", provider: "Dr. Michael Torres", reason: "Cardiology Annual Review" },
    ],
  },
  sources: [
    { name: "Memorial Health Clinic", lastSynced: "2025-12-16T08:00:00Z" },
    { name: "Downtown Cardiology", lastSynced: "2025-12-14T10:30:00Z" },
    { name: "Regional Medical Center", lastSynced: "2025-12-10T14:15:00Z" },
  ],
  disclaimer: "This document is generated from patient-authorized health record sources. Information is for clinical reference only and should be verified with original medical records. Generated by Tabula Medica - Patient Health Record Platform.",
};

function generateProviderPDF(data: PatientSummaryData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).font("Helvetica-Bold").text("Patient Health Summary", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica").fillColor("#666666").text("Provider Reference Document", { align: "center" });
    doc.moveDown(1);

    doc.rect(50, doc.y, 512, 80).fillAndStroke("#f5f5f5", "#e0e0e0");
    doc.fillColor("#000000");
    const infoY = doc.y + 10;
    doc.fontSize(12).font("Helvetica-Bold").text(`Patient: ${data.patientName}`, 60, infoY);
    doc.font("Helvetica").text(`Date of Birth: ${new Date(data.dateOfBirth).toLocaleDateString()}`, 60, infoY + 18);
    doc.text(`MRN: ${data.mrn}`, 60, infoY + 36);
    doc.text(`Generated: ${new Date(data.generatedDate).toLocaleDateString()}`, 60, infoY + 54);
    doc.y = infoY + 80;

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Health Overview");
    doc.moveDown(0.3);
    doc.fontSize(10).font("Helvetica").fillColor("#000000").text(data.summary.overallHealth, { lineGap: 3 });

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Active Conditions");
    doc.moveDown(0.3);
    data.summary.activeConditions.forEach((condition) => {
      doc.fontSize(10).font("Helvetica").fillColor("#000000").text(`• ${condition}`, { indent: 10 });
    });

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Current Medications");
    doc.moveDown(0.3);
    data.summary.currentMedications.forEach((med) => {
      doc.fontSize(10).font("Helvetica").fillColor("#000000").text(`• ${med.name} ${med.dose} - ${med.frequency}`, { indent: 10 });
    });

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Allergies");
    doc.moveDown(0.3);
    data.summary.allergies.forEach((allergy) => {
      doc.fontSize(10).font("Helvetica").fillColor("#dc2626").text(`• ${allergy}`, { indent: 10 });
    });

    doc.addPage();

    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Recent Laboratory Results");
    doc.moveDown(0.3);
    const labTableTop = doc.y;
    const labTableHeaders = ["Test", "Result", "Date", "Status"];
    const labColWidths = [150, 120, 100, 100];
    let labX = 50;
    labTableHeaders.forEach((header, i) => {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#000000").text(header, labX, labTableTop);
      labX += labColWidths[i];
    });
    doc.moveDown(0.5);
    let labRowY = doc.y;
    data.summary.recentLabs.forEach((lab) => {
      labX = 50;
      doc.fontSize(9).font("Helvetica").fillColor("#000000");
      doc.text(lab.name, labX, labRowY, { width: labColWidths[0] - 10 });
      doc.text(lab.value, labX + labColWidths[0], labRowY, { width: labColWidths[1] - 10 });
      doc.text(new Date(lab.date).toLocaleDateString(), labX + labColWidths[0] + labColWidths[1], labRowY, { width: labColWidths[2] - 10 });
      doc.fillColor(lab.status === "Normal" ? "#16a34a" : lab.status === "Improved" ? "#2563eb" : "#ca8a04")
        .text(lab.status, labX + labColWidths[0] + labColWidths[1] + labColWidths[2], labRowY, { width: labColWidths[3] - 10 });
      doc.fillColor("#000000");
      labRowY += 18;
    });
    doc.y = labRowY;

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Recent Visits");
    doc.moveDown(0.3);
    data.summary.recentVisits.forEach((visit) => {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#000000").text(`${new Date(visit.date).toLocaleDateString()} - ${visit.reason}`, { indent: 10 });
      doc.fontSize(9).font("Helvetica").fillColor("#666666").text(`${visit.provider} at ${visit.facility}`, { indent: 20 });
      doc.moveDown(0.3);
    });

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Immunization History");
    doc.moveDown(0.3);
    data.summary.immunizations.forEach((imm) => {
      doc.fontSize(10).font("Helvetica").fillColor("#000000").text(`• ${imm.name} - ${new Date(imm.date).toLocaleDateString()}`, { indent: 10 });
    });

    doc.moveDown(1);
    doc.fontSize(14).font("Helvetica-Bold").fillColor("#1a56db").text("Data Sources");
    doc.moveDown(0.3);
    data.sources.forEach((source) => {
      doc.fontSize(9).font("Helvetica").fillColor("#666666").text(`• ${source.name} (Last synced: ${new Date(source.lastSynced).toLocaleDateString()})`, { indent: 10 });
    });

    doc.moveDown(2);
    doc.rect(50, doc.y, 512, 60).fillAndStroke("#fff7ed", "#fed7aa");
    doc.fillColor("#92400e").fontSize(8).font("Helvetica").text(data.disclaimer, 60, doc.y + 10, { width: 492, lineGap: 2 });

    doc.end();
  });
}

export function registerProviderPacketRoutes(app: Express): void {
  app.get("/api/provider-packet/summary", async (req: Request, res: Response) => {
    try {
      const user = (req as any).user;
      const userId = user?.claims?.sub || "current-user";

      logPhiAccess({
        userId,
        patientId: "patient-default",
        resourceType: "ProviderPacket",
        action: "read",
        details: "VIEW_PROVIDER_SUMMARY",
      });

      res.json({ success: true, data: samplePatientSummary });
    } catch (error) {
      console.error("[ProviderPacket] Error fetching summary");
      res.status(500).json({ error: "Failed to fetch provider summary" });
    }
  });

  app.get("/api/provider-packet/download", async (req: Request, res: Response) => {
    try {
      const user = (req as any).user;
      const userId = user?.claims?.sub || "current-user";

      logPhiAccess({
        userId,
        patientId: "patient-default",
        resourceType: "ProviderPacket",
        action: "export",
        details: "DOWNLOAD_PROVIDER_PDF",
      });

      const pdfBuffer = await generateProviderPDF(samplePatientSummary);

      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="patient-summary-${new Date().toISOString().split("T")[0]}.pdf"`);
      res.setHeader("Content-Length", pdfBuffer.length);
      res.send(pdfBuffer);
    } catch (error) {
      console.error("[ProviderPacket] Error generating PDF");
      res.status(500).json({ error: "Failed to generate provider packet" });
    }
  });

  app.post("/api/provider-packet/share", async (req: Request, res: Response) => {
    try {
      const user = (req as any).user;
      const userId = user?.claims?.sub || "current-user";
      const { recipientEmail, recipientName, expiresInDays = 7 } = req.body;

      if (!recipientEmail || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipientEmail)) {
        return res.status(400).json({ error: "Invalid email address" });
      }

      logPhiAccess({
        userId,
        patientId: "patient-default",
        resourceType: "ProviderPacket",
        action: "export",
        details: `SHARE_WITH_PROVIDER: ${recipientEmail}`,
      });

      const shareToken = `share-${Date.now()}-${Math.random().toString(36).substring(2, 10)}`;
      const expiresAt = new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000).toISOString();

      res.json({
        success: true,
        data: {
          shareToken,
          shareUrl: `https://tabulamedica.app/share/${shareToken}`,
          recipientEmail,
          recipientName,
          expiresAt,
          message: `A secure link has been created for ${recipientName || recipientEmail}. They can access your health summary until ${new Date(expiresAt).toLocaleDateString()}.`,
        },
      });
    } catch (error) {
      console.error("[ProviderPacket] Error creating share link");
      res.status(500).json({ error: "Failed to create share link" });
    }
  });

  console.log("[Routes] Provider Packet routes registered at /api/provider-packet/*");
}
