// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/appstore-screenshots/Landscape.tsx": () => import("../components/mockups/appstore-screenshots/Landscape.tsx"),
  "./components/mockups/appstore-screenshots/Portrait.tsx": () => import("../components/mockups/appstore-screenshots/Portrait.tsx"),
  "./components/mockups/compliance-dashboard/Accessible.tsx": () => import("../components/mockups/compliance-dashboard/Accessible.tsx"),
  "./components/mockups/compliance-dashboard/Hierarchy.tsx": () => import("../components/mockups/compliance-dashboard/Hierarchy.tsx"),
  "./components/mockups/compliance-dashboard/Interaction.tsx": () => import("../components/mockups/compliance-dashboard/Interaction.tsx"),
  "./components/mockups/landing-redesign/BoldHealthcare.tsx": () => import("../components/mockups/landing-redesign/BoldHealthcare.tsx"),
  "./components/mockups/landing-redesign/ClinicalModern.tsx": () => import("../components/mockups/landing-redesign/ClinicalModern.tsx"),
  "./components/mockups/landing-redesign/RefreshedLanding.tsx": () => import("../components/mockups/landing-redesign/RefreshedLanding.tsx"),
  "./components/mockups/landing-redesign/WarmPremium.tsx": () => import("../components/mockups/landing-redesign/WarmPremium.tsx")
};
