import { storage } from "../storage";
import type { EhrPatientSource, EhrPlatform } from "@shared/schema";
import {
  computeIdentityMatch,
  shouldMerge,
  weakerConfidence,
  type IdentityCandidate,
  type MatchConfidence,
} from "./patient-identity-matching";
import { logger } from "../utils/logger";

export interface NewPatientSource extends IdentityCandidate {
  ehrConnectionId: string;
  platform: EhrPlatform;
  facilityName: string;
  mrn: string;
}

/**
 * The outcome of matching a new EHR source against this account's other
 * connections, BEFORE the internal Patient row exists. `unifiedPatientId` is
 * always populated — either an existing UnifiedPatient to merge into, or a
 * freshly-created one with no ehrSources yet. Callers MUST call
 * attachEhrSourceToUnifiedPatient() after storage.createPatient() to record
 * the source with its real internal patient id; until then the
 * UnifiedPatient has no source for this connection.
 */
export interface PatientIdentityMatch {
  unifiedPatientId: string;
  matchConfidence: MatchConfidence;
  isNewUnifiedPatient: boolean;
}

/**
 * Resolve which UnifiedPatient a newly-pulled EHR Patient record belongs to,
 * for a given account — WITHOUT yet knowing the internal Patient.id (that's
 * only generated by storage.createPatient(), which must run after this).
 * Compares the new record's identity fields against every OTHER EHR
 * connection already linked to this account; if exactly one matches
 * confidently enough (see patient-identity-matching), returns that identity.
 * A tie between two DIFFERENT people's UnifiedPatients at the same best
 * confidence is NOT positive identification — iteration order is not a
 * disambiguator — so a tie is treated the same as no match: create a new
 * identity rather than guess.
 */
export async function resolveUnifiedPatientForNewSource(
  userId: string,
  candidate: NewPatientSource,
): Promise<PatientIdentityMatch> {
  const connections = await storage.getEhrConnections(userId);
  // getEhrConnections(userId) also returns legacy/seed "current-user"
  // connections regardless of which userId was asked for — never let a real
  // account get matched against demo data (or another account's data) by
  // relying on that broadening.
  const otherConnections = connections.filter(
    c => c.userId === userId && c.id !== candidate.ehrConnectionId,
  );

  // Track every UnifiedPatient that reaches the best confidence seen so far;
  // more than one at the end means an unresolvable tie.
  let bestConfidence: MatchConfidence = "none";
  const bestCandidates = new Set<string>();

  for (const connection of otherConnections) {
    const existingPatients = await storage.getPatientsByConnection(connection.id);
    for (const existing of existingPatients) {
      if (!existing.unifiedPatientId) continue;
      const { confidence } = computeIdentityMatch(candidate, existing);
      if (!shouldMerge(confidence)) continue;
      if (CONFIDENCE_RANK(confidence) > CONFIDENCE_RANK(bestConfidence)) {
        bestConfidence = confidence;
        bestCandidates.clear();
        bestCandidates.add(existing.unifiedPatientId);
      } else if (confidence === bestConfidence) {
        bestCandidates.add(existing.unifiedPatientId);
      }
    }
  }

  if (bestCandidates.size === 1) {
    const [unifiedPatientId] = Array.from(bestCandidates);
    logger.info(
      `[PatientIdentity] matched connection ${candidate.ehrConnectionId} to existing unified patient ${unifiedPatientId} (confidence=${bestConfidence})`,
    );
    return { unifiedPatientId, matchConfidence: bestConfidence, isNewUnifiedPatient: false };
  }

  if (bestCandidates.size > 1) {
    logger.warn(
      `[PatientIdentity] ${bestCandidates.size}-way tie at confidence=${bestConfidence} for connection ${candidate.ehrConnectionId}; declining to auto-merge, creating a new identity`,
    );
  }

  const newUnified = await storage.createUnifiedPatient({
    firstName: candidate.firstName,
    middleName: "UNK",
    lastName: candidate.lastName,
    dateOfBirth: candidate.dateOfBirth,
    gender: "other",
    email: candidate.email ?? "",
    phone: candidate.phone ?? "",
    address: "",
    ehrSources: [],
    // A brand-new identity with no linked source yet has nothing to
    // corroborate or contradict it, so it starts at "high" — the same
    // convention used when no cross-source matching is even attempted.
    matchConfidence: "high",
  });
  logger.info(
    `[PatientIdentity] created new unified patient ${newUnified.id} for connection ${candidate.ehrConnectionId}`,
  );
  return { unifiedPatientId: newUnified.id, matchConfidence: "high", isNewUnifiedPatient: true };
}

/**
 * Record an EHR source on a UnifiedPatient AFTER storage.createPatient() has
 * run, using the real internal Patient.id — never the external MRN. Callers
 * downstream (getAggregatedPatientData and friends) match records by
 * comparing MedicalRecord.patientId against ehrSources[].patientId, which
 * only works when that field holds the internal id createPatient generated.
 */
export async function attachEhrSourceToUnifiedPatient(
  match: PatientIdentityMatch,
  source: Omit<EhrPatientSource, "lastSync"> & { lastSync?: string },
): Promise<void> {
  const unified = await storage.getUnifiedPatient(match.unifiedPatientId);
  if (!unified) {
    logger.error(`[PatientIdentity] attachEhrSource: unified patient ${match.unifiedPatientId} vanished`);
    return;
  }
  const fullSource: EhrPatientSource = { lastSync: new Date().toISOString(), ...source };
  const alreadyLinked = unified.ehrSources.some(s => s.ehrConnectionId === fullSource.ehrConnectionId);
  const ehrSources = alreadyLinked
    ? unified.ehrSources.map(s => (s.ehrConnectionId === fullSource.ehrConnectionId ? fullSource : s))
    : [...unified.ehrSources, fullSource];

  // A brand-new UnifiedPatient's confidence was set by resolveUnifiedPatientForNewSource
  // and has nothing to weaken against on its very first source; an existing
  // one aggregates to the WEAKER of its prior confidence and this match, so
  // linking on weaker evidence later can never inflate the overall rating.
  const matchConfidence = match.isNewUnifiedPatient
    ? unified.matchConfidence
    : (weakerConfidence(unified.matchConfidence, match.matchConfidence) as "high" | "medium" | "low");

  await storage.updateUnifiedPatient(match.unifiedPatientId, { ehrSources, matchConfidence });
}

function CONFIDENCE_RANK(c: MatchConfidence): number {
  return { high: 3, medium: 2, low: 1, none: 0 }[c];
}
